jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk
      ANDROID_HOME:      ${{ runner.tool_cache }}/android-sdk
      PATH: |
        ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin:
        ${{ env.ANDROID_SDK_ROOT }}/platform-tools:
        ${{ env.PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Android SDK
        run: |
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT --update
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

      - name: Generate local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Verify SDK setup
        run: |
          echo "local.properties:"
          cat android/local.properties
          echo "SDK content:"
          ls -R $ANDROID_SDK_ROOT

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Disable Daemon & Parallel
        run: |
          echo "org.gradle.daemon=false" >> android/gradle.properties
          echo "org.gradle.parallel=false" >> android/gradle.properties
          echo "org.gradle.configureondemand=false" >> android/gradle.properties

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew clean assembleDebug \
          --no-daemon --no-parallel --info --stacktrace
