// frontend/src/components/SpotTheDifference.js
import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import './styles/SpotTheDifference.css';

// The path to the local levels JSON file, which is now generated by our workflow.
const LEVELS_JSON_PATH = '/generated_levels/levels.json';

const GameStateDisplay = ({ message, isLoading = false, onRetry }) => (
    <div className="game-state-container">
        {isLoading && <div className="loader"></div>}
        <p>{message}</p>
        {onRetry && <button onClick={onRetry}>重试</button>}
    </div>
);

const DifferenceMarker = ({ diff, scaleFactor }) => {
    // Note: The original images might not be 1024px wide.
    // The coordinates are absolute, so we need to know the original image size
    // to correctly scale the markers. Let's assume the generated coordinates
    // are based on the actual size of the images in generated_levels.
    const style = {
        left: `${(diff.x / (diff.imageWidth || 1024)) * 100}%`,
        top: `${(diff.y / (diff.imageHeight || 1024)) * 100}%`,
        width: `${diff.radius * 2 * scaleFactor}px`,
        height: `${diff.radius * 2 * scaleFactor}px`,
        transform: 'translate(-50%, -50%)',
    };
    return <div className="difference-marker" style={style} />;
};


const GameImage = ({ src, onClick, children }) => {
    return (
        <div className="image-wrapper" onClick={onClick}>
            <img src={src} alt="Spot the difference" />
            {children}
        </div>
    );
};

const SpotTheDifference = () => {
    const navigate = useNavigate();
    const [levels, setLevels] = useState([]);
    const [currentLevelIndex, setCurrentLevelIndex] = useState(0);
    const [foundDifferences, setFoundDifferences] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState(null);
    const [imageScaleFactor, setImageScaleFactor] = useState(1);
    const [imageNaturalSize, setImageNaturalSize] = useState({ width: 1024, height: 1024 });


    const loadLevels = useCallback(async () => {
        setIsLoading(true);
        setError(null);
        try {
            // Fetch levels from the local JSON file.
            // Adding a cache-busting query parameter is good practice.
            const response = await fetch(`${LEVELS_JSON_PATH}?cachebust=${new Date().getTime()}`);
            if (!response.ok) {
                throw new Error(`Could not load level data. Status: ${response.status}`);
            }
            const loadedLevels = await response.json();
            
            if (!Array.isArray(loadedLevels) || loadedLevels.length === 0) {
                 throw new Error("No levels found. Please add images to 'images_for_ai' and run the workflow.");
            }

            // Shuffle the levels for variety
            const shuffledLevels = [...loadedLevels].sort(() => Math.random() - 0.5);
            setLevels(shuffledLevels);

        } catch (err) {
            console.error("Failed to load levels:", err);
            setError(err.message);
        } finally {
            setIsLoading(false);
            setCurrentLevelIndex(0);
            setFoundDifferences([]);
        }
    }, []);

    useEffect(() => {
        loadLevels();
    }, [loadLevels]);
    
    const currentLevel = useMemo(() => levels[currentLevelIndex], [levels, currentLevelIndex]);
    const differences = useMemo(() => currentLevel?.differences || [], [currentLevel]);
    const isLevelComplete = useMemo(() => differences.length > 0 && foundDifferences.length === differences.length, [foundDifferences, differences]);
    const isGameComplete = useMemo(() => isLevelComplete && currentLevelIndex === levels.length - 1, [isLevelComplete, currentLevelIndex, levels.length]);

    const handleImageClick = useCallback((e) => {
        if (isLevelComplete || !currentLevel) return;

        const imgElement = e.currentTarget.querySelector('img');
        if (!imgElement) return;
        
        // Ensure the natural dimensions of the image are loaded
        if (imgElement.naturalWidth === 0) {
            console.warn("Image natural width is 0, click might be inaccurate.");
            return;
        }

        const rect = imgElement.getBoundingClientRect();
        const scale = imgElement.clientWidth / imgElement.naturalWidth;
        setImageScaleFactor(scale);

        // Calculate click coordinates relative to the original image size
        const x = (e.clientX - rect.left) / scale;
        const y = (e.clientY - rect.top) / scale;

        differences.forEach((diff, index) => {
            if (foundDifferences.includes(index)) return;
            const distance = Math.sqrt(Math.pow(x - diff.x, 2) + Math.pow(y - diff.y, 2));
            if (distance < diff.radius) {
                setFoundDifferences(prev => [...new Set([...prev, index])]);
            }
        });
    }, [isLevelComplete, currentLevel, differences, foundDifferences]);
    
    const goToLevel = useCallback((index) => {
        if (index >= 0 && index < levels.length) {
            setCurrentLevelIndex(index);
            setFoundDifferences([]);
        }
    }, [levels.length]);

    const handleRestartGame = useCallback(() => {
        loadLevels(); // Reload and reshuffle levels
    }, [loadLevels]);
    
    // Add an effect to get the natural dimensions of the current level's image
    useEffect(() => {
        if (currentLevel?.original) {
            const img = new Image();
            img.onload = () => {
                setImageNaturalSize({ width: img.naturalWidth, height: img.naturalHeight });
            };
            img.src = currentLevel.original;
        }
    }, [currentLevel]);


    if (isLoading) return <GameStateDisplay message="正在加载关卡..." isLoading={true} />;
    if (error) return <GameStateDisplay message={error} onRetry={loadLevels} />;
    if (!currentLevel) return <GameStateDisplay message="没有可玩的关卡，请先上传图片。" onRetry={handleRestartGame} />;

    return (
        <div className="spot-the-difference-container">
            <header className="game-header">
                <button className="back-button" onClick={() => navigate('/')}>&lt; 退出</button>
                <div className="game-info">
                    <h1>{currentLevel.name} (关卡 {currentLevelIndex + 1} / {levels.length})</h1>
                    <p>找到的差异: {foundDifferences.length} / {differences.length}</p>
                </div>
            </header>

            <main className="images-container">
                <GameImage src={currentLevel.original} onClick={handleImageClick}>
                    {foundDifferences.map(index => {
                        const diff = differences[index];
                        return <DifferenceMarker key={`${index}-original`} diff={{...diff, imageWidth: imageNaturalSize.width, imageHeight: imageNaturalSize.height}} scaleFactor={imageScaleFactor} />
                    })}
                </GameImage>
                <GameImage src={currentLevel.modified} onClick={handleImageClick}>
                     {foundDifferences.map(index => {
                        const diff = differences[index];
                        return <DifferenceMarker key={`${index}-modified`} diff={{...diff, imageWidth: imageNaturalSize.width, imageHeight: imageNaturalSize.height}} scaleFactor={imageScaleFactor} />
                    })}
                </GameImage>
            </main>

            <footer className="game-footer">
                {isGameComplete ? (
                    <button className="game-button accent" onClick={handleRestartGame}>🎉 恭喜通关！再玩一次 🎉</button>
                ) : isLevelComplete ? (
                    <button className="game-button primary" onClick={() => goToLevel(currentLevelIndex + 1)}>✔️ 太棒了！下一关</button>
                ) : (
                     <div className="level-controls">
                        <button className="game-button" onClick={() => goToLevel(currentLevelIndex - 1)} disabled={currentLevelIndex === 0}>上一关</button>
                        <button className="game-button" onClick={() => goToLevel(currentLevelIndex + 1)} disabled={currentLevelIndex >= levels.length - 1}>下一关</button>
                    </div>
                )}
            </footer>
        </div>
    );
};

export default SpotTheDifference;
