name: Android CI/CD Optimized

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # 1. 前端编译
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Upload Frontend Assets
        uses: actions/upload-artifact@v4
        with:
          name: frontend-assets
          path: frontend/build

  # 2. Debug 构建
  android-debug:
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: frontend-assets
          path: android/app/src/main/assets
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-debug-${{ hashFiles('**/android/**/build.gradle*','**/android/gradle-wrapper.properties') }}
      - name: Build Debug APK
        run: |
          cd android
          ./gradlew clean assembleDebug --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk

  # 3. Release 构建并签名
  android-release:
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Frontend Assets
        uses: actions/download-artifact@v4
        with:
          name: frontend-assets
          path: android/app/src/main/assets

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-release-${{ hashFiles('**/android/**/build.gradle*','**/android/gradle-wrapper.properties') }}

      - name: Decode & Place Keystore into Android App
        run: |
          # 解码 keystore 并放到 android/app 目录
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > android/app/release-key.jks
          chmod 600 android/app/release-key.jks

          # 在 android/ 下生成 keystore.properties，storeFile 指向 app/release-key.jks
          cat <<EOF > android/keystore.properties
          storeFile=app/release-key.jks
          storePassword=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}
          EOF

      - name: Build & Sign Release APK
        run: |
          cd android
          ./gradlew clean assembleRelease --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk

  # 4. 自动发布到 GitHub Releases
  publish-release:
    needs: android-release
    runs-on: ubuntu-latest
    steps:
      - name: Download Release APK
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: release-artifacts

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release-artifacts/*.apk
          tag: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
