name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Correct Asset Paths for Android
      run: |
        INDEX_FILE="frontend/build/index.html"
        sed -i 's|href="./static/|href="/android_asset/static/|g' $INDEX_FILE
        sed -i 's|src="./static/|src="/android_asset/static/|g' $INDEX_FILE

    - name: Sync Frontend to Android Assets
      run: |
        rm -rf android/app/src/main/assets/*
        cp -r frontend/build/* android/app/src/main/assets/

    - name: ** Force Restore Gradle Wrapper Files **
      run: |
        echo "==> Restoring official gradlew script..."
        curl -o android/gradlew https://raw.githubusercontent.com/gradle/gradle/v8.7.0/gradlew
        echo "==> Restoring official gradle-wrapper.jar..."
        curl -o android/gradle/wrapper/gradle-wrapper.jar https://repo.gradle.org/gradle/8.7/wrapper/gradle-wrapper.jar
        echo "==> Files restored. Verifying..."
        ls -l android/gradlew
        ls -l android/gradle/wrapper/gradle-wrapper.jar

    - name: Build APK
      run: |
        chmod +x android/gradlew
        cd android
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
