name: Android CI + Emulator Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-build:
    name: 构建前端
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 缓存 node_modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}

      - name: 安装并打包前端
        run: |
          cd frontend
          npm ci
          npm run build

      - name: 修补 index.html：修改 base href 并去除 "./" 前缀
        run: |
          sed -i -E '
            s|<base href="[^"]*"|<base href="file:///android_asset/www/"|;
            s|src="\./|src="|g;
            s|href="\./|href="|g
          ' frontend/build/index.html

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/

  android-debug:
    name: 构建 Debug APK
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 准备 assets/www 目录
        run: mkdir -p android/app/src/main/assets/www

      - uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: android/app/src/main/assets/

      - name: 移动前端文件到 www
        run: |
          rm -rf android/app/src/main/assets/www
          mkdir -p android/app/src/main/assets/www
          mv android/app/src/main/assets/index.html android/app/src/main/assets/www/
          mv android/app/src/main/assets/static android/app/src/main/assets/www/

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-debug-${{ runner.os }}-${{ hashFiles('android/**/*.gradle*','android/gradle-wrapper.properties') }}

      - name: Assemble Debug APK
        run: |
          cd android
          ./gradlew clean assembleDebug --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk

  validate-assets:
    name: 校验 APK 资源
    needs: android-debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-debug
          path: ./apk

      - run: sudo apt-get update -y && sudo apt-get install -y unzip

      - name: 列出 assets 目录
        run: |
          unzip -l apk/*.apk | grep "assets/www/index.html" || exit 1
          unzip -l apk/*.apk | grep "assets/www/static/js" || exit 1

  emulator-test:
    name: 模拟器抓取 Logcat
    needs: android-debug
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: app-debug
          path: ./app-debug

      - name: 安装 Android SDK Command-line Tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip libgl1-mesa-dev libpulse0
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip \
            -o cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/latest

      - name: 安装 SDK 平台 & 模拟器镜像
        run: |
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$PATH
          yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses
          sdkmanager --sdk_root=${ANDROID_SDK_ROOT} \
            "platform-tools" \
            "emulator" \
            "platforms;android-31" \
            "system-images;android-31;google_apis_playstore;x86_64"

      - name: 创建并启动 AVD
        run: |
          avdmanager create avd --name ci --package "system-images;android-31;google_apis_playstore;x86_64" --force
          nohup emulator -avd ci -no-window -no-audio -accel off -gpu swiftshader_indirect &

      - name: 等待 Emulator 启动
        run: |
          adb kill-server && adb start-server
          for i in {1..60}; do
            if adb shell getprop sys.boot_completed | grep -q 1; then
              echo "Emulator 已启动"
              break
            fi
            echo "等待模拟器启动 ($i/60)"
            sleep 5
          done
          adb devices

      - name: 安装 APK & 抓取 Logcat
        run: |
          adb install -r app-debug/*.apk
          sleep 10
          adb logcat -d | grep -E "MainActivity|原始 HTML|修补后 HTML" > emulator-logcat.txt

      - uses: actions/upload-artifact@v4
        with:
          name: emulator-logcat
          path: emulator-logcat.txt
