# 文件：.github/workflows/android-cicd.yml
name: Android CI/CD Optimized

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # 1. 前端编译：生成 React 静态资源到 frontend/build
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install & Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/**

  # 2. Android Debug：合并前端资源并打包调试 APK
  android-debug:
    needs: frontend-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Frontend Build to assets/www
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: android/app/src/main/assets/www

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-debug-${{ runner.os }}-${{ hashFiles('android/**/build.gradle*','android/gradle-wrapper.properties') }}

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew clean assembleDebug --no-daemon

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk

  # 3. Android Release：签名打包 Release APK
  android-release:
    needs: frontend-build
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PATH: android/app/release-key.jks
      KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
      KEY_ALIAS:        ${{ secrets.SIGNING_KEY_ALIAS }}
      KEY_PASSWORD:     ${{ secrets.SIGNING_KEY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Frontend Build to assets/www
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: android/app/src/main/assets/www

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-release-${{ runner.os }}-${{ hashFiles('android/**/build.gradle*','android/gradle-wrapper.properties') }}

      - name: Decode & Place Keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" \
            | base64 -d > $KEYSTORE_PATH
          chmod 600 $KEYSTORE_PATH

      - name: Build & Sign Release APK
        run: |
          cd android
          ./gradlew clean assembleRelease \
            -Pandroid.injected.signing.store.file="$PWD/$KEYSTORE_PATH" \
            -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASSWORD" \
            --no-daemon

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk

  # 4. 自动发布到 GitHub Releases
  publish-release:
    needs: android-release
    runs-on: ubuntu-latest
    steps:
      - name: Download Release APK
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: release-artifacts

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release-artifacts/*.apk
          tag: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
