name: Android CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-build:
    name: Build Frontend Assets
    runs-on: ubuntu-22.04
    outputs:
      build-hash: ${{ steps.hash.outputs.build-hash }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install and build frontend
        run: |
          cd frontend
          npm ci
          PUBLIC_URL='./' npm run build

      - name: Generate frontend build hash
        id: hash
        run: |
          HASH=$(
            find frontend/build -type f -exec sha256sum {} + \
            | sort | sha256sum | cut -d' ' -f1
          )
          echo "build-hash=$HASH" >> $GITHUB_OUTPUT

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/

  android-build:
    name: Build Android APKs
    runs-on: ubuntu-22.04
    needs: frontend-build
    outputs:
      versionName: ${{ steps.ver.outputs.versionName }}
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate version info
        id: ver
        run: |
          VN="1.0.${GITHUB_RUN_NUMBER}"
          echo "versionCode=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "versionName=${VN}" >> $GITHUB_ENV
          echo "versionName=${VN}" >> $GITHUB_OUTPUT

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: android/app/src/main/assets/www

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Restore keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d \
            > android/app/release-key.jks

      - name: Build Release APK
        run: |
          cd android
          ./gradlew clean assembleRelease \
            -Pandroid.injected.signing.store.file=app/release-key.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.SIGNING_KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.SIGNING_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.SIGNING_KEY_PASSWORD }} \
            --no-daemon --stacktrace

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug \
            --no-daemon --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Publish Release
    needs: android-build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download Release APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: .

      - name: Generate checksum
        id: checksum
        run: |
          S=$(sha256sum app-release.apk | cut -d' ' -f1)
          echo "sha256=$S" >> $GITHUB_OUTPUT

      - name: Prepare Release Notes
        run: |
          cat << 'EOF' > release_notes.md
          ### Android App v${{ needs.android-build.outputs.versionName }}
          **Build Number**: ${{ github.run_number }}
          **Frontend Hash**: ${{ needs.frontend-build.outputs.build-hash }}
          **Release SHA256**: `${{ steps.checksum.outputs.sha256 }}`
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.android-build.outputs.versionName }}
          name: Release v${{ needs.android-build.outputs.versionName }}
          body_path: release_notes.md
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prerelease:
    name: Publish Prerelease
    needs: android-build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Download Debug APK
        uses: actions/download-artifact@v4
        with:
          name: debug-apk
          path: .

      - name: Generate checksum-beta
        id: checksum-beta
        run: |
          S=$(sha256sum app-debug.apk | cut -d' ' -f1)
          echo "sha256=$S" >> $GITHUB_OUTPUT

      - name: Prepare Prerelease Notes
        run: |
          cat << 'EOF' > prerelease_notes.md
          ### Android App v${{ needs.android-build.outputs.versionName }}-beta
          **Build Number**: ${{ github.run_number }}
          **Frontend Hash**: ${{ needs.frontend-build.outputs.build-hash }}
          **Debug SHA256**: `${{ steps.checksum-beta.outputs.sha256 }}`
          EOF

      - name: Create GitHub Prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.android-build.outputs.versionName }}-beta.${{ github.run_number }}
          name: Prerelease v${{ needs.android-build.outputs.versionName }}-beta
          body_path: prerelease_notes.md
          files: app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
