name: Android CI + Emulator Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # … 你的 frontend-build、android-debug、android-release jobs …

  # 新增：在 GitHub Runner 上启动 Android 模拟器，安装 APK，并抓 logcat
  emulator-test:
    name: Run Emulator & Capture Logcat
    needs: android-debug     # 或需要 app-debug 构建成功
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .  # 仓库根

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Debug APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug
          path: ./apk

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK & Emulator
        uses: android-actions/setup-android@v2
        with:
          api-level: 31                    # 你想要的 Android API
          target: google_apis              # 带 Google APIs 的模拟器
          arch: x86_64
          emulator-options: "-no-window -no-audio"

      - name: Start emulator
        run: |
          # 启动 headless 模拟器
          echo "no" | avdmanager create avd -n ci -k "system-images;android-31;google_apis;x86_64" --force
          nohup emulator -avd ci -no-window -no-audio -gpu swiftshader_indirect &

      - name: Wait for device
        run: |
          adb wait-for-device
          # 等待系统启动完成
          until adb shell getprop sys.boot_completed | grep -m 1 "1"; do
            echo "Waiting for emulator to boot..."
            sleep 5
          done

      - name: Install APK on emulator
        run: adb install -r ./apk/*.apk

      - name: Give it time to render
        run: sleep 10

      - name: Capture logcat filtered
        run: |
          adb logcat -d \
            | grep -E "MainActivity|Page start|Page finish|Load error|HTTP error|JS Console" \
            > emulator-logcat.txt

      - name: Upload Logcat Artifact
        uses: actions/upload-artifact@v4
        with:
          name: emulator-logcat
          path: emulator-logcat.txt
